export const GET_FOOTPRINT_LIST = 'GET_FOOTPRINT_LIST'
export const SET_FOOTPRINT_LIST = 'SET_FOOTPRINT_LIST'
export const SET_FOOTPRINT_CARBON = 'SET_FOOTPRINT_CARBON'
export const SET_FOOTPRINT_LIST_LOADING = 'SET_FOOTPRINT_LIST_LOADING'